#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $ANIE_REPO == "Aniebots" ]]
    then
        echo "aHR0cDovL0dpdGh1Yi5jb20vc2hpd2Fib3QvQW5pZWJvdC9hcmNoaXZlL21haW4uemlw=" | base64 -d
    elif [[ $ANIE_REPO == "Aniebots" ]]
    then
        echo "aHR0cDovL0dpdGh1Yi5jb20vc2hpd2Fib3QvQW5pZWJvdC9hcmNoaXZlL21haW4uemlw=" | base64 -d
    elif [[ $ANIE_REPO =~ $regex ]]
    then
        if [[ $ANIE_REPO_BRANCH ]]
        then
            echo "${ANIE_REPO}/archive/${MEOW_REPO_BRANCH}.zip"
        else
            echo "${ANIE_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cDovL0dpdGh1Yi5jb20vc2hpd2Fib3QvQW5pZWJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="Aniebot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    ANIEPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $ANIEPATH
    echo "  • Starting Aniebots •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m Aniebots 
}

start_bot
