#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $ANIEX_REPO == "Anie-userbot" ]]
    then
        echo "aHR0cDovL2dpdGh1Yi5jb20vc2hpd2Fib3QvQW5pZWJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $ANIEX_REPO == "Anie-userbot" ]]
    then
        echo "aHR0cDovL2dpdGh1Yi5jb20vc2hpd2Fib3QvQW5pZWJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $ANIEX_REPO =~ $regex ]]
    then
        if [[ $ANIEX_REPO_BRANCH ]]
        then
            echo "${ANIEX_REPO}/archive/${ANIEX_REPO_BRANCH}.zip"
        else
            echo "${ANIEX_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cDovL2dpdGh1Yi5jb20vc2hpd2Fib3QvQW5pZWJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="Aniebot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    ANIEPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $ANIEXPATH
    echo "    Starting Anie-Userbot    "
    echo "
    ┏━━━┓          ┏┓    ┏┓
    ┃┏━┓┃          ┃┃   ┏┛┗┓
    ┃┃ ┃┣┓┏┳━┳━━┳┓┏┫┗━┳━┻┓┏┛
    ┃┗━┛┃┃┃┃┏┫┏┓┣╋╋┫┏┓┃┏┓┃┃
    ┃┏━┓┃┗┛┃┃┃┏┓┣╋╋┫┗┛┃┗┛┃┗┓
    ┗┛ ┗┻━━┻┛┗┛┗┻┛┗┻━━┻━━┻━┛  

    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m Anie-Userbot
}

_set_bot
